spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dividend
    username: root
    password: tjddnr12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: c3ByaW5nLWJvb3QtZGl2aWRlbmQtcHJvamVjdC1qd3Qtc2VjcmV0LWtleQo=

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"




